version: '3.5'
      
services:
  odect: 
    container_name: odect
    image: odect:latest
    volumes:
      - "./data/:/app/odect/data"
    environment:
      - ODECT_API_KNMI=here-your-knmi-api-key-without-quotes
      - ODECT_API_ENTSOE=here-your-entsoe-api-key-without-quotes
      - ODECT_N_DAYS=3
      - ODECT_INFLUXURL=http://odect_influx
      - ODECT_INFLUXPORT=8086
      - ODECT_INFLUXDB=odect
